COPYING
README.md

Let me try in smaller steps :-) Here a proposal to clarify the licensing of this project by adding the license text and a comments in the readme.

added some details about copyright and licensing (see #11)

---

app/src/main/res/layout/activity_login.xml

This was already in Android Design library.
A simple attribute made the job !

Added show password toggle in login activity

---

app/src/main/res/layout/account_row.xml
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/activity_launcher.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_manage_accounts.xml
app/src/main/res/layout/activity_privacy_policy.xml
app/src/main/res/layout/drawer_header.xml
app/src/main/res/layout/item_album.xml
app/src/main/res/values-v21/styles.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

The new colors referenced in the files should now match the iOS colors..
See issue #107

Modified colors and layouts to match Piwigo official colors

---

app/src/main/java/org/piwigo/PiwigoApplication.java
app/src/main/java/org/piwigo/helper/NetworkHelper.java

Added some helper class to check if the user has internet access.
It is easy to use and accessible from everywhere.
Closes #91

Added helper class for internet status

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Just a quick update of Gradle.. :)

Updated gradle files to use Gradle 5.1.1

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/piwigo/bg/AlbumService.java
app/src/main/java/org/piwigo/internal/di/module/AndroidInjectorModule.java
app/src/main/java/org/piwigo/io/RestService.java
app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/main/res/menu/drawer_main.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

I created a new Service called "AlbumService" to handle album creation.
It may be reused for renaming, deleting, and moving album in the future.
It is for now just a button in the drawer, but it could also be added into a FAB context menu.. (see issue #104)
The only problem for now is the album list is not refreshing, something which should be reviewed in another issue..
Thank you :)

Added the ability to create some albums from the app

---

app/build.gradle
app/src/main/java/org/piwigo/ui/main/AlbumItemViewModel.java
app/src/main/java/org/piwigo/ui/main/AlbumsFragment.java
app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/menu/drawer_main.xml
app/src/main/res/menu/fab_menu.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Replaced the "Upload" and "Create button" by a FAB which offers the same options.
Behavior:
When the user is on the album list, he can only pick "Create an album".
When he enters and album / sub-album, he can now choose either "Upload photos" or "Create a sub-album".
Planning:
Maybe a progressbar around the FAB ?..

Replaced drawer buttons by a FAB

---

app/src/main/java/org/piwigo/helper/URLHelper.java
app/src/main/java/org/piwigo/ui/login/LoginViewModel.java
app/src/main/res/values/strings.xml

Some cleanup after #120 review

Some needed cleanup, and missing infos

---

.travis.yml
app/build.gradle
app/src/main/java/org/piwigo/ui/login/LoginViewModel.java
app/src/main/res/layout/activity_main.xml
app/src/test/java/org/piwigo/PiwigoApplicationTest.java
app/src/test/java/org/piwigo/accounts/UserManagerTest.java
app/src/test/java/org/piwigo/ui/login/LoginViewModelTest.java

Android 10 is brand new and not very well supported yet.
Still I find a way to get the tests to work again.

Fixing Travis-CI

---

app/build.gradle
app/src/main/res/values/strings.xml

This should really help to fix some memory leaks issues related to the way we load pictures.
Closes #133 .

Added LeakCanary library for further memory leaks debug

---

app/build.gradle
app/src/main/java/org/piwigo/helper/TouchImageView.java
app/src/main/java/org/piwigo/internal/di/module/AndroidInjectorModule.java
app/src/main/java/org/piwigo/internal/di/module/ApplicationModule.java
app/src/main/java/org/piwigo/ui/main/AlbumsViewModel.java
app/src/main/java/org/piwigo/ui/main/ImagesItemViewModel.java
app/src/main/java/org/piwigo/ui/photoviewer/PhotoViewerDialogFragment.java
app/src/main/java/org/piwigo/ui/photoviewer/PhotoViewerDialogFragmentModule.java
app/src/main/java/org/piwigo/ui/photoviewer/PhotoViewerPagerAdapter.java
app/src/main/java/org/piwigo/ui/photoviewer/TouchImageView.java
app/src/main/res/layout/fragment_fullscreen_images.xml
app/src/main/res/layout/item_fullscreen_image.xml
app/src/main/res/layout/item_images.xml

This is a simple photoviewer with swiping and zooming features.
This could and should be very much improved in the future.

Implemented a simple photoviewer

---

app/build.gradle
app/src/main/java/org/piwigo/PiwigoApplication.java
app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/test/java/org/piwigo/PiwigoApplicationTest.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

I updated some version of used libraries. @voriondev can you give it a try and merge if ok?

bump versions

---

app/src/main/java/org/piwigo/bg/UploadService.java
app/src/main/java/org/piwigo/io/event/SnackProgressEvent.java
app/src/main/java/org/piwigo/io/model/ImageUploadItem.java
app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/main/res/values/strings.xml

A few fixes for the single file upload and the snackprogressbar behavior (bug related to #148)..
Some code cleanup too.
@ramack Could you please take a quick look if anything jump to your eyes ?

Fix single file upload

---

app/src/main/java/org/piwigo/ui/login/LoginViewModel.java
app/src/main/java/org/piwigo/ui/main/AlbumsFragment.java
app/src/main/java/org/piwigo/ui/main/AlbumsViewModel.java
app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/main/play/release-notes/en-US/default.txt
app/src/main/res/values-fr/strings.xml

changes in MainActivity should fix #152, sorry for the mess to include a few translations, but finally we'll need them anyhow, so I'd like to skip spending the effort to cleaning up the tree here

cleanup backstack

---

app/src/main/java/org/piwigo/bg/AlbumService.java
app/src/main/java/org/piwigo/bg/UploadService.java
app/src/main/java/org/piwigo/helper/NotificationHelper.java
app/src/main/java/org/piwigo/io/model/AddCategoryResponse.java
app/src/main/java/org/piwigo/io/model/ImageUploadResponse.java

show more details in case of upload failure

---

app/src/main/java/org/piwigo/ui/login/LoginActivity.java

Added veryfing if fabProgressCircle is null before calling a function from it.. hopefully it would fix #167

Check if fabProgressCircle != null

---

app/src/main/java/org/piwigo/io/model/ImageInfo.java

May fix #168 as it is a pretty common error (seen a lot on stackoverflow for instance).

Made ImageInfo.java implements Serializable to avoid RuntimeException

---

app/src/main/java/org/piwigo/bg/UploadService.java
app/src/main/java/org/piwigo/io/model/ImageInfo.java

Should fix #173 as it is directly related.. still we need to find a better solution than a dirty workaround..

Checking if response's body is empty 

---

build.gradle

Update Gradle to 3.5.2

---

app/src/main/java/org/piwigo/ui/photoviewer/TouchImageView.java

Should fix sliding when image is zoomed.. 
Still to do:

WIP #186 - improve slide and zoom behavior

---

app/src/main/java/org/piwigo/PiwigoApplication.java
app/src/main/java/org/piwigo/io/repository/PreferencesRepository.java
app/src/main/java/org/piwigo/ui/login/LoginActivity.java
app/src/main/java/org/piwigo/ui/settings/SettingsActivity.java
app/src/main/res/layout/account_row.xml
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/activity_launcher.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_manage_accounts.xml
app/src/main/res/layout/activity_privacy_policy.xml
app/src/main/res/layout/drawer_header.xml
app/src/main/res/layout/item_album.xml
app/src/main/res/menu/fab_menu.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values-v21/styles.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/xml/settings_preferences.xml

Dark color palette

---

app/src/main/java/org/piwigo/PiwigoApplication.java
app/src/main/java/org/piwigo/helper/URLHelper.java
app/src/main/java/org/piwigo/ui/login/LoginViewModel.java

Instead of checking HTTPS port and HTTP port, we are now making dumb requests directly to the designated Piwigo server.

#205 Better protocol detection

---

app/src/main/java/org/piwigo/ui/login/LoginViewModel.java
app/src/test/java/org/piwigo/ui/login/LoginViewModelTest.java

Recalling "testConnection" method does kill the test thread.

Fix unit testing

---

app/build.gradle
app/src/androidTest/java/org/piwigo/ui/login/LoginTest.java

I setup https://tg1.kulow.org with 3 galleries. One public visible
to everyone, one small for 'seessmall:seessmall' to see and one large
for 'seeslarge:seeslarge' to see.
The espresso test adds both accounts

Add espresso test handling 2 accounts on the same gallery

---

.travis.yml
app/src/androidTest/java/org/piwigo/ui/login/LoginTest.java

Add integration tests to travis

---

app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/main/java/org/piwigo/ui/main/MainViewModel.java
app/src/main/res/menu/drawer_main.xml
app/src/main/res/values/strings.xml

The logout functionality does not really match with the account manager.
Login needs to happen transparently, our 'Login' screen is basically
creating accounts. More cleanup to follow

Remove logout menu item

---

app/src/main/java/org/piwigo/PiwigoApplication.java

The popup is annoying in debugging :)

Disable ACRA on debug builds

---

app/src/main/java/org/piwigo/bg/AlbumService.java
app/src/main/java/org/piwigo/bg/UploadService.java
app/src/main/java/org/piwigo/data/repository/CategoriesRepository.java
app/src/main/java/org/piwigo/data/repository/ImageRepository.java
app/src/main/java/org/piwigo/io/WebServiceFactory.java
app/src/main/java/org/piwigo/io/restmodel/LoginResponse.java
app/src/main/java/org/piwigo/io/restrepository/RESTCategoriesRepository.java
app/src/main/java/org/piwigo/io/restrepository/RESTImageRepository.java
app/src/main/java/org/piwigo/io/restrepository/RestUserRepository.java
app/src/main/java/org/piwigo/ui/login/LoginActivity.java
app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/test/java/org/piwigo/io/restrepository/RestUserRepositoryTest.java

Some functions won't work anyway if the passed account isn't the current account, so plainly rely on the current account everywhere

Don't pass the account around like a hot potato

---

app/src/androidTest/java/org/piwigo/ui/login/LoginTest.java
app/src/main/java/org/piwigo/accounts/UserManager.java
app/src/main/java/org/piwigo/data/repository/CategoriesRepository.java
app/src/main/java/org/piwigo/data/repository/ImageRepository.java
app/src/main/java/org/piwigo/io/restrepository/RestUserRepository.java
app/src/main/java/org/piwigo/ui/account/AccountViewModel.java
app/src/main/java/org/piwigo/ui/account/ManageAccountsActivity.java
app/src/main/java/org/piwigo/ui/account/ManageAccountsViewModel.java
app/src/main/java/org/piwigo/ui/login/LoginViewModel.java
app/src/main/java/org/piwigo/ui/main/AlbumsViewModel.java
app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/main/java/org/piwigo/ui/main/MainViewModel.java
app/src/test/java/org/piwigo/ui/login/LoginViewModelTest.java

It's too racy - the database contains the name of the account as well

Rework login handling (rebase finished)

---

.idea/jarRepositories.xml
.idea/modules.xml
app/build.gradle
app/src/androidTest/java/org/piwigo/ui/fullscreen/FullScreenTest.java
app/src/androidTest/java/org/piwigo/ui/login/LoginTest.java
app/src/main/java/org/piwigo/EspressoIdlingResource.java
app/src/main/java/org/piwigo/accounts/UserManager.java
app/src/main/java/org/piwigo/ui/login/LoginActivity.java
app/src/main/java/org/piwigo/ui/login/LoginViewModel.java
app/src/main/java/org/piwigo/ui/main/AlbumsViewModel.java
app/src/main/java/org/piwigo/ui/main/MainActivity.java
app/src/main/java/org/piwigo/ui/main/MainViewModel.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

This simplifies the tests as we do not need to sleep or retry

Add idle resource for login handling to verify we're idle
